### ISSUE TITLE
SHOW TABLES

### ISSUE THREAD

**Issue by dannyvolkaerts** [shafayetShafee/interactive-sql#2]
Hi,

Thank you for the nice extention! I like using it for my courses.
One question though:

How can I use the SHOW TABLES command?
In SQLite it should be .tables or tables but I can't manage to run this without error.

Thank you!

**Comment by shafayetShafee** [comment]
Yes, `.tables` is not working on the [SQLite playground (sqlime)](https://sqlime.org/) either. And `interactive-sql` is using that playground behind the scene. So `.tables` won't work.  

In that case, try the command 

``` sql
SELECT * FROM sqlite_master WHERE type = 'table';
```

**Comment by dannyvolkaerts** [comment]
ok, thank you - that does the job

**Comment by shafayetShafee** [comment]
I am closing the issue then.
